
sudo: false
language: python
os: osx
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "nightly"
  - "pypy"
  - "pypy3"
script: python test/suite.py
branches:
  only:
    - master
