
language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "nightly"
  - "pypy"
  - "pypy3"
install:
  - pip install codecov
  - python setup.py install
script:
  - python test/suite.py
after_success:
  - python run test/suite.py
  - codecov
